name: Package and Push to Downloads

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install zip
      run: sudo apt-get update && sudo apt-get -qq install zip

    - name: Create zip file
      run: zip -r currentVersion.zip . -x "*.git/*" ".gitignore" ".github/*"
      
    - name: Upload to SFTP server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.SERVER_USERNAME }}
        server: ${{ secrets.SERVER_HOST }}
        password: ${{ secrets.SERVER_PASSWORD }}
        local_path: "./currentVersion.zip"
        remote_path: ${{ secrets.SERVER_PATH }}
        args: "-o ConnectionTimeout=5"

    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.4
      with:
        sftp: true
        host: ${{ secrets.SERVER_HOST }}
        port: 22
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        remote_folder: ${{ secrets.SERVER_PATH }}
        local_folder: '.'
        cleanup: false
        include: '[currentVersion.zip]'
        exclude: '["node_modules/**", "_secret.php", ".github/**", ".git/**", "*.env"]'
        pasive: true

    - name: Delete zip file
      run: rm -r currentVersion.zip
