name: Package and Push to Downloads

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install zip
      run: sudo apt-get update && sudo apt-get -qq install zip

    - name: Create zip file
      run: zip -r currentVersion.zip . -x "*.git/*" ".gitignore" ".github/*"

    - name: Upload to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: "[2a02:8071:a583:1fe0:461e:a1ff:fe39:5c48]"
        username: singleziphost
        password: singleziphost
        server-dir: /usr/share/caddy
        local-dir: .
        exclude: '**/*'
        include: 'currentVersion.zip'

    - name: Delete zip file
      run: rm currentVersion.zip
