name: Package and Push to Downloads

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install zip
      run: sudo apt-get update && sudo apt-get -qq install zip

    - name: Create directory for zip file
      run: mkdir zipdir

    - name: Create zip file
      run: zip -r zipdir/currentVersion.zip . -x "*.git/*" ".gitignore" ".github/*"

    - name: Upload to SFTP server
      uses: easingthemes/gh-action-sftp@master
      with:
        host: "sftp://[2a02:8071:a583:1fe0:461e:a1ff:fe39:5c48]"
        username: singleziphost
        password: singleziphost
        localDir: "zipdir"
        remoteDir: "/usr/share/caddy"
        args: "-avz --delete"

    - name: Delete zip file
      run: rm -r zipdir
