name: Package and Push to Downloads

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install zip
      run: sudo apt-get update && sudo apt-get -qq install zip

    - name: Create zip file
      run: zip -r currentVersion.zip . -x "*.git/*" ".gitignore" ".github/*"
      

    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.4
      with:
        sftp: true
        host: "95.208.227.27"
        port: 61000
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        remote_folder: ${{ secrets.SERVER_PATH }}
        local_folder: '.'
        cleanup: false
        include: '["currentVersion.zip"]'

    - name: Delete zip file
      run: rm -r currentVersion.zip
