name: Push to Server
on:
  push:
    branches:
      - server
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload Mods to MC server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.SERVER_USERNAME }}
        server: ${{ secrets.SERVER_HOST }}
        password: ${{ secrets.SERVER_PASSWORD }}
        local_path: "./mods/*"
        remote_path: "/opt/mcsmanager/daemon/data/InstanceData/6d526b16b87a412abc64e1a333062829/mods"
        delete_remote_files: true
        args: "-o ConnectionTimeout=5"

    - name: Upload Config to MC server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.SERVER_USERNAME }}
        server: ${{ secrets.SERVER_HOST }}
        password: ${{ secrets.SERVER_PASSWORD }}
        local_path: "./config/*"
        remote_path: "/opt/mcsmanager/daemon/data/InstanceData/6d526b16b87a412abc64e1a333062829/config"
        delete_remote_files: false
        args: "-o ConnectionTimeout=5"
