name: Build Server Branch

on:
  push:
    branches:
      - main

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Setup Git User
        run: |
          git config --global user.name 'QuantenQuentchen'
          git config --global user.email 'qquentchen@gmail.com'

      - name: Clear and Transfer Folders
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            const exec = require('child_process').execSync;
            const foldersToTransfer = ['folder1', 'folder2']; // Replace with your folder names
            const excludeFile = 'serversYesYes.txt'; // Replace with your file name

            // Read the exclude file and create a list of files to exclude
            const excludeFiles = fs.readFileSync(excludeFile, 'utf-8').split('\n').filter(Boolean);

            // Checkout to the 'server' branch and remove all files
            exec('git checkout server');
            exec('git rm -r *');

            // Checkout back to the main branch and copy the folders excluding the files
            exec('git checkout main');
            foldersToTransfer.forEach(folder => {
              exec(`git checkout server -- ${folder}`);
              excludeFiles.forEach(file => {
                exec(`git rm --cached ${folder}/${file}`);
              });
            });

            // Commit and push the changes
            exec('git commit -m "Transfer folders"');
            exec('git push origin server');
