name: Sync Branches to server deploy branch

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Setup Git User
        run: |
          git config --global user.name 'QuantenQuentchen'
          git config --global user.email 'qquentchen@gmail.com'

      - name: Debug
        run: |
          echo "Git Status:"
          git status
          echo "Git Branch:"
          git branch

      - name: Sync branches and commit changes
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            const exec = require('child_process').execSync;
            const excludeFile = 'serverNoNos.txt'; // File with paths to exclude
            // Read the exclude file and create a list of paths
            const excludePaths = fs.readFileSync(excludeFile, 'utf-8').split('\n').filter(Boolean);
            // Checkout to the 'server' branch and merge the 'main' branch
            exec('git checkout server');
            try {
              exec('git merge -s recursive -X ours main');
            } catch (error) {
              console.error('Merge failed:', error);
              process.exit(1);
            }
            // Remove the excluded paths
            excludePaths.forEach(path => {
              try {
                exec(`git rm --cached ${path}`);
            } catch (error) {
                console.error('Failed to remove ${path}:', error);
            }
            });
            // Commit and push the changes
            exec('git commit -m "Sync with main branch"');
            exec('git push origin server');
